import type { Metadata } from "next";
import { TASA_Orbiter } from "next/font/google";
import "./globals.css";

const tasa = TASA_Orbiter({
  variable: "--font-neuton",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tasa.variable} antialiased`}>{children}</body>
    </html>
  );
}
